### ISSUE TITLE
Регистрация / Вход

### ISSUE THREAD

**Issue by artemzi** [STC12-team/BookSharingProject#20]
1. Создать страницу с формой регистрации
 - продумать процесс регистрации и подтверждения (для отправки email можно использовать например mailtrap.io)

2. Создать страницу с формой входа

// TODO: нужно ли описывать детали или на усмотрение того, кто будет заниматься реализацией ?

**Comment by svdovin** [comment]
реализовано в рамках регистрации пользователя #29
