### ISSUE TITLE
Авторизация для администратора

### ISSUE THREAD

**Issue by bass-2000** [STC12-team/BookSharingProject#26]
Я как АДМИНИСТРАТОР хочу войти в суперсекретную часть системы, чтобы иметь полномочия администратора.

Подключить Security Manager (через XML)
Алгоритм разграничения доступа на страницы (контекст в XML)
Страница с формой логина
Страница с ошибкой входа
Страница с разлогином (выход)

**Comment by svdovin** [comment]
будет реализовано в миграциях
