### ISSUE TITLE
Я как ПОЛЬЗОВАТЕЛЬ, хочу иметь возможность заходить в профиль для просмотра своих персональных данных

### ISSUE THREAD

**Issue by svdovin** [STC12-team/BookSharingProject#86]
Только просмотр, не редактирование.

0) Сделать картинку и согласовать со всеми (хоть на бумажке)
1) Должна быть создана страница "Профиль"
2) Ограничение на вход - только юзер и админ
3) Отображение информации:
- логин
- ФИО
- email

**Comment by artemzi** [comment]
![](https://habrastorage.org/webt/bj/f4/mk/bjf4mkrzaze3ixp3jtuhfijsixe.png)
